### NumPy
- Library for working with arrays
- support for n-dimensional arrays
- useful in data science

In [2]:
!pip install numpy

In [3]:
import numpy as np

### 1. Create

In [4]:
data = np.random.rand(2,3,4)
zeroes = np.zeros((2,2,2))
full = np.full((2,2,2),7)
ones = np.ones((2,2,2))

In [9]:
ones

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [10]:
arr = np.array([[1,2,3,4],[1,2,3,4]])

In [12]:
type(arr)

numpy.ndarray

### 2. Read

In [14]:
# Attributes
shape = data.shape
size = data.size
types = data.dtype

In [17]:
types

dtype('float64')

In [28]:
arr = data[0]
slicer = data[0:2]
slicerr = data[0][0:2]
slicerrr = data[0][0][0:2]
reverse = data[-1]
singleval = data[0][0][0]

In [29]:
slicerrr

array([0.78448058, 0.1142822 ])

### 3. Update

In [30]:
list1 = np.random.rand(10)
list2 = np.random.rand(10)

In [32]:
list2

array([0.26068464, 0.63835896, 0.96212842, 0.55405275, 0.71459168,
       0.36058828, 0.80037947, 0.79839315, 0.30025306, 0.20642789])

In [33]:
# Basic Math
add = np.add(list1, list2)
sub = np.subtract(list1, list2)
div = np.divide(list1, list2)
mult = np.multiply(list1, list2)
dot = np.dot(list1, list2)

In [39]:
dot

2.6621307900645017

In [41]:
# Statistical Functions
sqrt = np.sqrt(25)
ab = np.abs(-2)
power = np.power(2,7)
log = np.log(25)
exp = ([2,4])
mins = np.min(list1)
maxs = np.max(list1)

In [43]:
data[0][0][0] = 1

In [44]:
data

array([[[1.        , 0.1142822 , 0.24284549, 0.4369313 ],
        [0.04370722, 0.63624404, 0.80652204, 0.20136584],
        [0.72111372, 0.19084844, 0.10071818, 0.71824752]],

       [[0.46421879, 0.75013285, 0.80590974, 0.60220881],
        [0.30802169, 0.36123011, 0.0597663 , 0.74061671],
        [0.35211759, 0.25970032, 0.29258044, 0.53297083]]])

In [46]:
data.sort()
data

array([[[0.1142822 , 0.24284549, 0.4369313 , 1.        ],
        [0.04370722, 0.20136584, 0.63624404, 0.80652204],
        [0.10071818, 0.19084844, 0.71824752, 0.72111372]],

       [[0.46421879, 0.60220881, 0.75013285, 0.80590974],
        [0.0597663 , 0.30802169, 0.36123011, 0.74061671],
        [0.25970032, 0.29258044, 0.35211759, 0.53297083]]])

In [47]:
data.shape

(2, 3, 4)

In [49]:
data = data.reshape((2,2,-1))  # -1 means that we don't care about this value
data.shape

(2, 2, 6)

In [50]:
zeroes = np.zeros((8))
print(zeroes)
zeroes = np.append(zeroes, [3,4])
print(zeroes)

[0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 3. 4.]


In [52]:
zeroes = np.insert(zeroes, 2, 1) #inserts 1 in 2nd index
print(zeroes)

[0. 0. 1. 1. 0. 0. 0. 0. 0. 0. 3. 4.]


### 4. Delete

In [53]:
data

array([[[0.1142822 , 0.24284549, 0.4369313 , 1.        , 0.04370722,
         0.20136584],
        [0.63624404, 0.80652204, 0.10071818, 0.19084844, 0.71824752,
         0.72111372]],

       [[0.46421879, 0.60220881, 0.75013285, 0.80590974, 0.0597663 ,
         0.30802169],
        [0.36123011, 0.74061671, 0.25970032, 0.29258044, 0.35211759,
         0.53297083]]])

In [55]:
np.delete(data, 0, axis=1) #which level of array we want to delete. axis = 1, specifying we want to delete row

array([[[0.63624404, 0.80652204, 0.10071818, 0.19084844, 0.71824752,
         0.72111372]],

       [[0.36123011, 0.74061671, 0.25970032, 0.29258044, 0.35211759,
         0.53297083]]])

In [57]:
np.save("new array", data) #saves the array as a file in the same directory

In [59]:
test = np.load("new array.npy")
test

array([[[0.1142822 , 0.24284549, 0.4369313 , 1.        , 0.04370722,
         0.20136584],
        [0.63624404, 0.80652204, 0.10071818, 0.19084844, 0.71824752,
         0.72111372]],

       [[0.46421879, 0.60220881, 0.75013285, 0.80590974, 0.0597663 ,
         0.30802169],
        [0.36123011, 0.74061671, 0.25970032, 0.29258044, 0.35211759,
         0.53297083]]])